version: '2'

services:
  mynodered:
    build: 
      context: ./docker/nodered
      dockerfile: Dockerfile
    ports:
      - "1899:1880"
    expose:
      - "1899"    
    volumes:
      - nodered_volume:/data
    container_name: trantek-nodered

  mymongo:
    image: "mongo:3.6.3"
    ports:
      - "27017:27017"
    volumes:
      - mongo_volume:/data/db
      - mongo_volume:/data/configdb
    container_name:   trantek-mongodb

  mypostgresql:
    image: "mdillon/postgis:11"
    ports:
      - "7432:5432"
    restart: always
    environment:
      POSTGRES_USER: trantek
      POSTGRES_PASSWORD: svv123svv
    volumes:
      - postgresql_volum:/var/lib/postgresql/data
    container_name:   trantek-postgres

  mynotebook:
    build: docker/jupyter
    volumes:
      - notebook_volume:/home/jovyan
    ports:
      - 9999:8888
    container_name:   trantek-jupyter

  mypgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=trantek@npra.io
      - PGADMIN_DEFAULT_PASSWORD=svv123svv
    ports:
      - 8080:80
    volumes:
      - pgadmin_volum:/var/lib/pgadmin
    container_name:   trantek-pgadmin

  mymongoexpress:
    image: mongo-express
    environment: 
      - ME_CONFIG_MONGODB_SERVER=trantek-mongodb
    ports:
      - 8081:8081
    restart: always
    container_name: trantek-mongoexpress


