version: '3.2'

services:
  mynodered:
    build: 
      context: ./docker/nodered
      dockerfile: Dockerfile
    ports:
      - "1899:1880"
    expose:
      - "1899"    
    volumes:
      - type: volume
        source: nodered_volume
        target: /data
    container_name: trantek-nodered

  mymongo:
    image: "mongo:3.6.3"
    ports:
      - "27017:27017"
    volumes:
      - type: volume
        source: mongo_volume
        target: /data/db
      
      - type: volume
        source: mongo_volume
        target: /data/configdb
    container_name:   trantek-mongodb

  mypostgresql:
    build: docker/postgresql
    ports:
      - "7432:5432"
    restart: always
    environment:
      POSTGRES_USER: trantek
      POSTGRES_PASSWORD: svv123svv
    volumes:
      - type: volume
        source: postgresql_volum
        target: /var/lib/postgresql/data
    container_name:   trantek-postgres

  mynotebook:
    build: docker/jupyter
    volumes:
      - type: bind
        source: ./work/notebooks/
        target: /home/jovyan/work
    ports:
      - 9999:8888
    container_name:   trantek-jupyter

  mypgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=trantek@npra.io
      - PGADMIN_DEFAULT_PASSWORD=svv123svv
    ports:
      - 8080:80
    volumes:
      - type: volume
        source: pgadmin_volum
        target: /var/lib/pgadmin
    container_name:   trantek-pgadmin

  mymongoexpress:
    image: mongo-express
    environment: 
      - ME_CONFIG_MONGODB_SERVER=trantek-mongodb
    ports:
      - 8081:8081
    container_name: trantek-mongoexpress

volumes:
  nodered_volume:
  mongo_volume:
  postgresql_volum:
  pgadmin_volum:

