version: '2'

services:
  mynodered:
    build: 
      context: ./docker/nodered
      dockerfile: Dockerfile
    restart: always
    ports:
      - "127.0.0.1:7001:1880"
    volumes:
      - nodered_volume:/data
    container_name: trantek-nodered

  mymongo:
    image: "mongo:4.4"
    restart: always
    ports:
      - "127.0.0.1:7003:27017"
    volumes:
      - mongo_volume:/data/db
      - mongo_volume:/data/configdb
    container_name:   trantek-mongodb

  mypostgresql:
    image: "postgis/postgis:12-master"
    ports:
      - "127.0.0.1:7004:5432"
    restart: always
    environment:
      POSTGRES_USER: trantek
      POSTGRES_PASSWORD: svv123svv
    volumes:
      - postgre_volume:/var/lib/postgresql/data
    container_name:   trantek-postgres

  mynotebook:
    build: docker/jupyter
    restart: always
    environment:
      - PASSWORD=svv123svv
    volumes:
      - notebook_volume:/home/jovyan
    ports:
      - 127.0.0.1:7002:8888
    container_name:   trantek-jupyter

  mypgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=trantek@npra.io
      - PGADMIN_DEFAULT_PASSWORD=svv123svv
    ports:
      - 127.0.0.1:7006:80
    volumes:
      - pgadmin_volum:/var/lib/pgadmin
    container_name:   trantek-pgadmin

  mymongoexpress:
    image: mongo-express
    restart: always
    environment: 
      - ME_CONFIG_MONGODB_SERVER=trantek-mongodb
    ports:
      - 127.0.0.1:7005:8081
    restart: always
    container_name: trantek-mongoexpress

volumes:
  nodered_volume:
  notebook_volume:
  mongo_volume:
  pgadmin_volum:
  postgre_volume:

