version: '3.4'

services:
  mynodered:
    build: 
      context: ./docker/nodered
      dockerfile: Dockerfile
    ports:
      - "1899:1880"
    expose:
      - "1899"    
    volumes:
      - type: volume
        source: nodered_volume
        target: /data
    container_name: nodered-trantek

  mymongo:
    image: "mongo:3.6.3"
    ports:
      - "27017:27017"
    volumes:
      - type: volume
        source: mongo_volume
        target: /data/db
      
      - type: volume
        source: mongo_volume
        target: /data/configdb
    container_name:   mongo-trantek

  mypostgresql:
    build: docker/postgresql
    ports:
      - "7432:5432"
    restart: always
    environment:
      POSTGRES_USER: trantek
      POSTGRES_PASSWORD: svv123svv
    volumes:
      - type: volume
        source: postgresql_volum
        target: /var/lib/postgresql/data
    container_name:   postgres-trantek

  datascience-notebook:
    build: docker/jupyter
    volumes:
      - type: bind
        source: ./work/notebooks
        target: /home/jovyan/work
    ports:
      - 9999:8888
    container_name:   jupyter-trantek


volumes:
  nodered_volume:
  mongo_volume:
  postgresql_volum:

