version: '3'
services:
  nodered:
    image: "nodered/node-red-docker"
    ports:
     - "1890:1880"
    expose:
     - "1890"
    volumes:
     - nodered_volume:/data

  mongo:
    image: "mongo:3.6.3"
    ports:
     - "27017:27017"
    volumes:
     - mongo_volume:/data/db
     - mongo_volume:/data/configdb

volumes:
 nodered_volume:
 mongo_volume:
