FROM nodered/node-red:latest

#FROM nodered/node-red-docker
#Justering for å få inn Node red

LABEL maintainer=tomas@levin.nu 

RUN npm install node-red-contrib-web-worldmap
RUN npm install node-red-contrib-mongodb3
